name    'Vglen-ohs'
version '0.1.1'
source 'git://github.com/vglen/ohs.git'
author 'Vglen'
license 'Apache License 2.0'
summary 'Puppet module for installing OHS'
description 'Allows to install OHS as a single instance or multiple ones using hiera'
project_page 'https://github.com/vglen/ohs'
